### ISSUE TITLE
Tuari 2.7 crashes when calling `panel.close ()` or `window.close ()`

### ISSUE THREAD

**Issue by qiuxchao** [ahkohd/tauri-nspanel#93]
Calling window.close() still results in a crash:

```rust
if let Ok(panel) = app.get_webview_panel("pop_panel") {
    panel.set_released_when_closed(true);
    if let Some(window) = app.get_webview_window("pop_panel") {
        window.close().unwrap();
    };
}
```

Tauri info:

```
[✔] Environment
    - OS: Mac OS 15.5.0 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.85.0 (4d91de4e4 2025-02-17)
    ✔ cargo: 1.85.0 (d73d2caf9 2024-12-31)
    ✔ rustup: 1.28.2 (e4f3ad6f8 2025-04-28)
    ✔ Rust toolchain: 1.85.0-aarch64-apple-darwin (default)
    - node: 20.18.2
    - pnpm: 9.15.1
    - yarn: 1.22.22
    - npm: 10.8.2

[-] Packages
    - tauri 🦀: 2.7.0
    - tauri-build 🦀: 2.3.1
    - wry 🦀: 0.52.1
    - tao 🦀: 0.34.0
    - @tauri-apps/api : 2.7.0
    - @tauri-apps/cli : 2.7.1

[-] Plugins
    - tauri-plugin-opener 🦀: 2.2.3, (outdated, latest: 2.4.0)
    - @tauri-apps/plugin-opener : 2.4.0
    - tauri-plugin-global-shortcut 🦀: 2.3.0
    - @tauri-apps/plugin-global-shortcut : 2.3.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

The smallest reproducible repository:https://github.com/qiuxchao/tauri-nspanel-demo

**Comment by ahkohd** [comment]
thanks for reporting I will look into it.

**Comment by ahkohd** [comment]
fixed in commit 040fd1d9d0c69cb384fa53fe32f1a7a95f0f2cc0

```rust
#[tauri::command]
fn close_panel(handle: AppHandle) {
  if let Ok(panel) = handle.get_webview_panel("mini-panel") {
    panel.set_released_when_closed(true);
    // release the event handler if any
    panel.set_event_handler(None);
    panel.close(&handle);
  }
}
```

run `cargo update -p tauri-nspanel`

demo:

https://github.com/user-attachments/assets/91808c10-41f2-462e-b571-a2b6abcaf02d

**Comment by qiuxchao** [comment]
It doesn't crash now, but the tauri window is not freed, so it can't be created with the same label again.

**Comment by ahkohd** [comment]
> It doesn't crash now, but the tauri window is not freed, so it can't be created with the same label again.

i will look into it.

**Comment by ahkohd** [comment]
Hello @qiuxchao, I have identified the issue and resolved it. The close API has changed; `panel.close()` is now removed. I have introduced a new API, `panel.to_window()`, which converts a panel back to a Tauri window. After this, we can call `window.close()`. This ensures that Tauri properly manages the window and cleans it up when we call `window.close()`.

```rust
#[tauri::command]
fn close_panel(app_handle: AppHandle) {
    app_handle
        .get_webview_panel("pop_panel")
        .ok()
        .and_then(|panel| panel.to_window())
        .map(|window| window.close());
}
```

See the commits from ecbfd7e to 50130fcf.

Demo:

https://github.com/user-attachments/assets/644b77b3-6ce0-4799-a737-71afc5173309

https://github.com/user-attachments/assets/ebf6bd4a-3768-4bf7-adc4-943f340706de


Run `cargo update -p tauri-nspanel` to the latest version and let me know if it resolves your issue.

**Comment by qiuxchao** [comment]
I updated the latest code, but it still crashes.

https://github.com/user-attachments/assets/3cbf9c30-b1a5-4c40-aadb-84af5216215e

**Comment by ahkohd** [comment]
> I updated the latest code, but it still crashes.
> 
>  _2025-09-08.103149.mp4

can you run `cargo clean`? clean previous cached data. also share the crash log. what is the macOS version. also try commenting out `to_panel` to see if it still crashes.

**Comment by ahkohd** [comment]
> > I updated the latest code, but it still crashes.
> > _2025-09-08.103149.mp4
> 
> can you run `cargo clean`? clean previous cached data. also share the crash log. what is the macOS version. also try commenting out `to_panel` to see if it still crashes.

try these:
<img width="483" height="213" alt="Image" src="https://github.com/user-attachments/assets/d341096e-ed3e-4500-b3e0-037f3b35c94b" />
<img width="986" height="175" alt="Image" src="https://github.com/user-attachments/assets/b392f4e5-01f9-4fa2-9228-12d5f55b7218" />

https://github.com/user-attachments/assets/c749baa4-9d28-49dd-b844-826b9ca147b2

**Comment by ahkohd** [comment]
If crash persists, try this branch:
```cargo
tauri-nspanel = { git = "https://github.com/ahkohd/tauri-nspanel", branch = "probe" }
```
let me know how it goes.

**Comment by qiuxchao** [comment]
I found the reason, because my entire application has only one panel and no other windows, so it crashes after I close it.

After I created a new normal window, it was fine.

Thanks for your work.

**Comment by ahkohd** [comment]
> I found the reason, because my entire application has only one panel and no other windows, so it crashes after I close it.
> 
> After I created a new normal window, it was fine.
> 
> Thanks for your work.

Interesting, it doesn’t crash on newer macOS version as shown in 
my demo even if the entire application has only one panel. 

Good to know. Im glad it’s resolved.
